campuses = {
    "Maliha Women's Campus": "MLW",
    "Sharjah Women's Camp Community": "SHW",
    "Al-Dhaid Women's Campus": "DHW",
    "Khorfakan Women's Campus": "KOW",
    "Deba Al Hesn Women's Campus": "DNW",
    "Maliha Men's Campus": "MLM",
    "Al-Dhaid Men's Campus": "DHM",
    "Kalba UOS Men's Campus": "KUM",
    "Kalba Men's Camp. Community": "KAM",
    "Medical Men's Campus": "MDM",
    "Kalba Women's Camp. Community": "KAW",
    "Khorfakan Men's Campus": "KOM",
    "FineArts Men's Campus": "FAM",
    "Kalba UOS Women's Campus": "KUW",
    "Sharjah Men's Camp Community": "SHM",
    "UOS Main Campus": "UOS",
    "UOS Men's Campus": "MAM",
    "UOS Women's Campus": "MAW"
}

collages = {
    "Shari'a & Islamic Studies": "01",
    "Arts, Humanities & Social Sci.": "02",
    "Business Administration": "03",
    "Engineering": "04",
    "Health Sciences": "05",
    "Law": "06",
    "Communication": "08",
    "Medicine": "09",
    "Pharmacy": "11",
    "Community": "12",
    "Sciences": "14",
}

departments = {
    "Physiotherapy": "PHTH",
    "Applied Physics": "APHY",
    "Mechanical Engineering": "MECH",
    "Health Services Administration": "HSAD",
    "Education": "EDUC",
    "Information Technology(Commun)": "INFO",
    "Computer Science": "COSC",
    "English Language Center": "IEP",
    "Pharmacy": "PHRM",
    "Health and Medical Sciences": "HMSC",
    "English Language & Literature": "ENGL",
    "Nuclear Engineering": "NUCL",
    "Financial & Administrative Sci": "FIAD",
    "Mass Communication": "MASS",
    "International Relations": "INRE",
    "Sociology": "SOCI",
    "Electrical/Electronic Eng.": "EECE",
    "Foundations of Religion": "FREL",
    "Basic Sciences(Community)": "BSCC",
    "Health Sciences/General": "HSGN",
    "Medicine": "MEDC",
    "Clinical Nutrition": "CLNU",
    "Communication": "COMM",
    "Accounting": "ACCT",
    "Medical Laboratory Technology": "MLT",
    "Mathematics": "MATH",
    "Medical Diagnostic Imaging": "MDI",
    "Nursing": "NURS",
    "Civil & Environ. Eng.": "CIVL",
    "Industrial Engn & Engn Managmt": "IEMG",
    "Public Relation": "PUBL",
    "General Medicine": "GMED",
    "Chemistry": "CHMS",
    "Computer Engineering": "CENG",
    "Master of Business Admin.": "MBA",
    "Environmental Health": "ENVH",
    "Law": "LAW",
    "History & Islamic Civilization": "HISL",
    "Mang. Info. Sys & Operations": "MIS",
    "Architectural Engineering": "ARCH",
    "Finance and Economics": "FNEC",
    "Management": "BUSP",
    "Arabic Language & Literature": "ARAB",
    "Jurisprudence & its Foundation": "JURF",
    "Sustainable/Renewable Enrg Eng": "SREE",
    "Applied Biology": "BIOT",
    "Public Law": "PBLW",
    "Private Law": "PRLW"
}

majors = {
    "Pharmacy": "PHAR",
    "Public Relations General": "PUBG",
    "Mass Communication": "MASS",
    "Sharia & Law": "SHLW",
    "Chemistry": "CHMS",
    "Applied Sociology": "ASOC",
    "Fashion Design & Textile": "FATX",
    "Law": "LAW",
    "Information Tech. - Multimedia": "ITME",
    "Nursing - Bdg": "NURB",
    "Accounting": "ACCT",
    "Mathematics": "MATH",
    "Communication": "COMM",
    "Petroleum Geosc & Remote Sens": "PTRL",
    "English Language & Literature": "ENGL",
    "Environmental Health": "ENUT",
    "Business Administration": "BADM",
    "Graphics  Design & Multimedia": "MMDS",
    "Sustainable/Renewable Enrg Eng": "SREE",
    "Finance": "FINB",
    "Nursing": "NURS",
    "Mass Communication(English)": "GMSC",
    "Electronic Media": "ELMD",
    "Electrical/Electronic Engr.": "EENG",
    "International Relations": "INRE",
    "Medical Diagnostic Imaging": "MDI",
    "Non Degree Undergraduate": "NDUG",
    "Exegesis & Quran Sciences (DR)": "EXQR",
    "Jurisprudence & its Foundation": "JURI",
    "Architectural Engineering": "AENG",
    "Dental Surgery": "DENT",
    "Hadit & its Sciences (DR)": "HDTH",
    "Medicine & Surgery": "MEDC",
    "Medical Diagnostic Imag - Bdg": "MDIB",
    "Information Technology": ["IT", "CDIT"],
    "Exegesis & Hadith": "EXGS",
    "Fine Arts": "FNAR",
    "Graphic Design": "GRDS",
    "Fundamentals of Jurisprudence": "FJUR",
    "Sociology": "SOCI",
    "History & Islamic Civilization": "HIST",
    "Civil Engineering": "CENG",
    "Public Law": "PBLW",
    "Physiotherapy": "PHYS",
    "Art History and Museum Studies": "HITM",
    "History & Civilization-Tourist": "HITO",
    "Management Information Systems": "MISM",
    "Computer Engineering": "CMEN",
    "Biotechnology": "BIOT",
    "Health Services Administration": "HSAD",
    "Medical Lab Sciences": "MLT",
    "Clinical Nutrition & Dietetics": "CLNU",
    "Private Law": "PRLW",
    "Applied Physics": "APHY",
    "Interior Architecture & Design": "INTD",
    "Foundations of Religion": "FREL",
    "Documentation & Archiving": "ARVE",
    "Public Relation": "PUBL",
    "Teaching": "TECH",
    "Arabic Language & Literature": "ARAB",
    "Translation": "TRAN",
    "Engr. Management & Innovation": "EMI",
    "Nuclear Engineering": "NSE",
    "Mechanical Engineering": "MENG",
    "Leadership in Health Pro. Educ": "LHPE",
    "Comparative Jurisprudence": "CJUR",
    "Common Business Program": "GBUS",
    "Molecular Medicine": "MOLM",
    "Industrial Engr & Engr Mngt": "IEMG",
    "Computer Science": "COMS",
    "Engineering Management": "ENMG",
    "Human Resource Management": "DPHR"
}

levels = {
    "Diploma": "DP",
    "Foundation Year": "FY",
    "General Diploma": "GD",
    "Higher Diploma": "HD",
    "Intensive English": "IE",
    "Master": "GR",
    "Medical Phase 2": "MD",
    "Medical Phase 3": "MF",
    "Undeclared": "00",
    "Undergraduate": "UG"
}
